### ISSUE TITLE
Lifecycle rules are not returned using purefb_info

### ISSUE THREAD

**Issue by winstonpickle** [Pure-Storage-Ansible/FlashBlade-Collection#204]
Lifecycle rules are not returned using purefb_info

**To Reproduce**
- name: collect all info
  purestorage.flashblade.purefb_info:
    gather_subset:
      - buckets
    fb_url: 10.10.10.2
    api_token: *****
  register: blade_info

**Expected behavior**
buckets with lifecycles runs to be returned in the following format
`            "test": {
                "account_name": "acme",
                "bucket_type": "classic",
                "created": 1630591952000,
                "data_reduction": 3.6,
                "destroyed": false,
                "id": "d5f6149c-fbef-f3c5-58b6-8fd143110ba9",
                "lifecycle_rules": {
                    "test": {
                        "abort_incomplete_multipart_uploads_after (days)": 1,
                        "cleanup_expired_object_delete_marker": true,
                        "enabled": true,
                        "keep_current_version_for (days)": null,
                        "keep_current_version_until": "2023-12-21",
                        "keep_previous_version_for (days)": null,
                        "prefix": "foo"
                    }`

**Actual** in ansible
AttributeError: 'ErrorResponse' object has no attribute 'items'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

get_lifecycle_rules doesn't appear to work as expected. This is using py-pure-client 1.29.0 against 

>>> all_rules = list(system.get_lifecycle_rules().items)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ErrorResponse' object has no attribute 'items'

**Comment by sdodsley** [comment]
Please provide the `ansible-playbook` output with the `-vvvv` switch

**Comment by winstonpickle** [comment]
Hey Simon, The error is the ansible mentioned. it difficult to give you the full vvvv as there's sensitive information in there.
AttributeError: 'ErrorResponse' object has no attribute 'items'\n",
"module_stdout": "",
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"rc": 1
}

**Comment by sdodsley** [comment]
At some point in the `-vvvv` output will be a stack trace - that is what i need to see.
If you do not want to put it in this public forum you can email me at simon@purestorage.com

**Comment by winstonpickle** [comment]
Simon, it's 3.3.3

**Comment by sdodsley** [comment]
OK - so i have just tested this on my 3.3.3 FB and the module works as expected.
Can you confirm the version of the FlashBlade Collection you are using? The latest is 1.10.0.
I have also tested the code line in Python directly and it works as expected.

**Comment by winstonpickle** [comment]
We are using 1.10.0 of the FlashBlade collection and py-pure-client 1.29.0. I can reproduce using only pypureclient
>>> from pypureclient import flashblade
>>> system = flashblade.Client(target=blade_name,api_token=api)
/home/******/lib/python3.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '******'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
>>> all_rules = list(system.get_lifecycle_rules().items)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ErrorResponse' object has no attribute 'items'

**Comment by sdodsley** [comment]
I saw that in your original messages.
I get it to work fine with py-pure-client 1.29.0 
Can you post the response to `system.get_lifecycle_rules()`

**Comment by sdodsley** [comment]
Oh - that's a good one. Never seen that before... 
Seems like we need to create a fix for this. I'll get on it and respond to this issue when I have a working patch

**Comment by sdodsley** [comment]
@winstonpickle please try #205 to see if it fixes your issue.

**Comment by winstonpickle** [comment]
Simon, Thanks that has fixed it. Appreciate your help.
